spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1/student?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=UTC

env: haha
